export const mockServices = [
    {
        id: 1,
        title: 'Cutting',
        description: "Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.",
        image: '/images/services/cutting.jfif',
        hoverImage: '/images/services/hover/cutting.jfif',
        isComing: false,
    },
    {
        id: 2,
        title: 'Edging',
        description: "Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.",
        image: '/images/services/edging.jfif',
        hoverImage: '/images/services/hover/edging.jfif',
        isComing: false,
    },
    {
        id: 3,
        title: 'Wood Processing',
        description: "Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.",
        image: '/images/services/processing.jfif',
        hoverImage: '/images/services/hover/processing.jfif',
        isComing: true,
    },
    {
        id: 4,
        title: 'Coating',
        description: "Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.",
        image: '/images/services/coating.jfif',
        hoverImage: '/images/services/hover/coating.jfif',
        isComing: true,
    },
    {
        id: 5,
        title: 'Ready-made Modules',
        description: "Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors. Committed to eco-friendly practices, we only source materials from sustainable vendors.",
        image: '/images/services/ready-made-modules.png',
        hoverImage: null,
        isComing: true,
    },
]