
export const mockServices = [
  {
    id: 1,
    title: 'cutting_title',
    description:"cutting_description",
    image: '/images/services/cutting.jfif',
    hoverImage: '/images/services/hover/cutting.jfif',
    isComing: false,
    bgPos: 'bottom',
    bgSize: '',
    hoverBgPos: '50px -200px',
    hoverBgSize: '500',
  },
  {
    id: 2,
    title: 'edging_title',
    description:'edging_description',
    image: '/images/services/edging.jfif',
    hoverImage: '/images/services/hover/edging.jpeg',
    isComing: false,
    bgPos: 'center',
    bgSize: '',
    hoverBgPos: '50px -220px',
    hoverBgSize: '100px',
  },
  {
    id: 3,
    title: 'wood_title',
    description:'wood_description',
    image: '/images/services/processing.jfif',
    hoverImage: '/images/services/hover/processing.jpeg',
    isComing: true,
    bgPos: 'center',
    bgSize: '',
    hoverBgPos: '150px -100px',
    hoverBgSize: '400',
  },
  {
    id: 4,
    title: 'coating_title',
    description:'coating_description',
    image: '/images/services/coating.jfif',
    hoverImage: '/images/services/hover/coating.jfif',
    isComing: true,
    bgPos: 'center',
    bgSize: '',
    hoverBgPos: '150px -100px',
    hoverBgSize: '420',
  },
];
