export const productsData = [
    {
        id: 1,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 2,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 3,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 4,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 5,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 6,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 7,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 8,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 9,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
    {
        id: 10,
        name: 'Maximera',
        category: 'kitchen',
        price: '47,000',
        color: '#FFFFFF',
        currency: 'AMD',
    },
];