export const facadeData = {
  facadePreferences: {
    name: 'Facade Preferences',
    items: [
      {
        id: 1,
        name: 'With',
        type: 'with',
        value: 1,
        editable: true,
        default: true,
        isFixed: false,
        selectable: true,
      },
      {
        id: 2,
        name: 'Without',
        type: 'without',
        value: 2,
        editable: true,
        isFixed: false,
        selectable: true,
      },
    ],
  },
  type: {
    name: 'Type',
    items: [
      {
        id: 1,
        name: 'Smooth',
        type: 'smooth',
        value: 1,
        editable: true,
        default: true,
        isFixed: false,
        selectable: true,
      },
      {
        id: 2,
        name: 'Framework',
        type: 'framework',
        value: 2,
        editable: true,
        isFixed: false,
        selectable: true,
      },
      {
        id: 3,
        name: 'Milled',
        type: 'milled',
        value: 2,
        editable: true,
        isFixed: false,
        selectable: true,
      },
      {
        id: 4,
        name: 'Glass',
        type: 'glass',
        value: 2,
        editable: true,
        isFixed: false,
        selectable: true,
      },
      {
        id: 5,
        name: 'Other',
        type: 'other',
        value: 2,
        editable: true,
        isFixed: false,
        selectable: true,
      },
    ],
  },
};
